# Generated by Django 6.0.2 on 2026-04-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='formation',
            field=models.CharField(default='DQP', max_length=255),
        ),
    ]
