# Generated by Django 6.0.2 on 2026-04-27 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accueil', '0004_evaluation_sequence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statut', models.CharField(max_length=10)),
                ('date', models.DateField(auto_now_add=True)),
                ('emploi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.emploidutemps')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accueil.student')),
            ],
        ),
    ]
