from django.urls import path
from . import views

urlpatterns = [
    path('', views.accueil, name='accueil'),
    path('connexion-etudiant/', views.connexion_etudiant, name='connexion_etudiant'),
    path('connexion-enseignant/', views.connexion_enseignant, name='connexion_enseignant'),
    path('dashboard-admin/', views.dashboard_admin, name='dashboard_admin'),
    path('etudiants/', views.students, name='etudiants'),
    path('deconnexion-etudiant/', views.deconnexion_etudiant, name='deconnexion_etudiant'),
    path('admin-login/', views.login_admin, name='login_admin'),
    path('admin-inscription/', views.inscription_admin, name='inscription_admin'),
    path('enseignants/', views.enseignants, name='enseignants'),
    path('filieres/', views.filieres, name='filieres'),
    path('cours/', views.cours, name='cours'),
    path('paiements/', views.paiements, name='paiements'),
    path('paiement/recu/<int:id>/', views.recu_paiement, name='recu_paiement'),
    path('emploi-du-temps/', views.emploi_du_temps, name='emploi_du_temps'),
    path('emploi-events/', views.emploi_events, name='emploi_events'),
    path('evaluation-teacher/', views.evaluation_teacher, name='evaluation_teacher'),
    path('get-evaluations/', views.get_evaluations, name='get_evaluations'),
    path('bulletin-etudiant/<int:etudiant_id>/', views.bulletin_etudiant, name='bulletin_etudiant'),
    path('delete-etudiant/<int:id>/', views.delete_etudiant, name='delete_etudiant'),
    path('edit-etudiant/<int:id>/', views.edit_etudiant, name='edit_etudiant'),
    path('delete-enseignant/<int:id>/', views.delete_enseignant, name='delete_enseignant'),
    path('edit-enseignant/<int:id>/', views.edit_enseignant, name='edit_enseignant'),
    path('delete-filiere/<int:id>/', views.delete_filiere, name='delete_filiere'),
    path('edit-filiere/<int:id>/', views.edit_filiere, name='edit_filiere'),
    path('delete-cours/<int:id>/', views.delete_cours, name='delete_cours'),
    path('edit-cours/<int:id>/', views.edit_cours, name='edit_cours'),
    path('emploitemps_enseignant/', views.emploitemps_enseignant, name='emploitemps_enseignant'),
    path('emploienseignant-events/', views.emploienseignant_events, name='emploienseignant_events'),
    path('presence/', views.presence_enseignant, name='presence_enseignant'),
    path('etudiants/<int:filiere_id>/',views.get_etudiants_filiere, name='get_etudiants_filiere'),
    path('save-presence/',views.save_presence,name='save_presence' ),
    path('presence-data/<int:emploi_id>/',views.presence_data, name='presence_data'),
    path('mes-cours/', views.mes_cours, name='mes_cours'),
    path('mon-emploi-du-temps/', views.mon_emploi_du_temps, name='mon_emploi_du_temps'),
    path('emploi-events-etudiant/', views.emploi_events_etudiant, name='emploi_events_etudiant'),
    path('mes-notes/', views.mes_notes, name='mes_notes'),
    path('mes-bulletins/', views.mes_bulletins, name='mes_bulletins'),
    path('mes-paiements/', views.mes_paiements, name='mes_paiements'),


]
